repoJB/routes/admin.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::get('',[HomeController::class,'index'])->name('inicio');

Route::resource('users',UserController::class)->only(['index','edit','update'])->names('admin.users');

repoJB/routes/web.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CicloController;
use App\Http\Controllers\PerfilController;
use App\Http\Controllers\ProyectoController;
use Illuminate\Support\Facades\Route;
use App\Models\Proyecto;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->user()) {
        return view('index');
    }
    return view('welcome');
})->name('home');

Route::middleware(['auth:sanctum', 'verified'])->get('ciclos', [CicloController::class, 'index'])->name('ciclos.index');

Route::middleware(['auth:sanctum', 'verified'])->get('ciclos/{ciclo}', [CicloController::class, 'show'])->name('ciclos.show');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/mis-proyectos', [ProyectoController::class, 'personales'])->name('proyectos.personales');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/step', [ProyectoController::class, 'step'])->name('proyectos.step');

Route::middleware(['auth:sanctum', 'verified'])->post('proyectos/{proyecto}/comentar', [ProyectoController::class, 'comentar'])->name('proyectos.comentar');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/{proyecto}/eliminarComentario', [ProyectoController::class, 'eliminarComentario'])->name('proyectos.eliminarComentario');

Route::resource('proyectos', ProyectoController::class)->names('proyectos')->middleware(['auth:sanctum', 'verified']);

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/{proyecto}/descargar', [ProyectoController::class, 'download'])->name('proyectos.download');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/{proyecto}/descargarLogo', [ProyectoController::class, 'descargarLogo'])->name('proyectos.descargarLogo');

Route::middleware(['auth:sanctum', 'verified'])->get('perfil/{user}', [PerfilController::class, 'index'])->name('perfil');

/*Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');*/

repoJB/app/Http/Livewire/Admin/UsersIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;
class UsersIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = "bootstrap";
    public $search;

    public function updatingSearch(){
        $this->resetPage();
    } 
    
    public function render()
    {
        /*$users = User::where('name','LIKE','%' . $this->search . '%')
        ->orWhere('email','LIKE','%' . $this->search . '%')
        ->paginate();*/
        $users = User::all();

        return view('livewire.admin.users-index',compact('users'));
    }
}

repoJB/app/Http/Livewire/CiclosIndex.php
<?php

namespace App\Http\Livewire;

use App\Models\Ciclo;
use Livewire\Component;
use Livewire\WithPagination;

class CiclosIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = "bootstrap";
    public $search;

    public function updatingSearch()
    {
        $this->resetPage();
    }
    public function render()
    {
        $ciclos = Ciclo::where('nombre', 'LIKE', '%' . $this->search . '%')
            ->orderBy('nombre')
            ->paginate(10);
        return view('livewire.ciclos-index', compact('ciclos'));
    }
}

repoJB/app/Http/Livewire/ProyectosIndex.php
<?php

namespace App\Http\Livewire;

use App\Models\Ciclo;
use App\Models\Proyecto;
use Livewire\Component;
use Livewire\WithPagination;

class ProyectosIndex extends Component
{

    use WithPagination;
    protected $paginationTheme = "bootstrap";
    public $search;

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $proyectos = Proyecto::latest('created_at')
            ->where('nombre', 'LIKE', '%' . $this->search . '%')
            ->paginate(10);
        return view('livewire.proyectos-index', compact('proyectos'));
    }
}

repoJB/app/Http/Livewire/ProyectosPersonales.php
<?php

namespace App\Http\Livewire;

use App\Models\Ciclo;
use App\Models\Proyecto;
use Livewire\Component;
use Livewire\WithPagination;


class ProyectosPersonales extends Component
{

    use WithPagination;
    protected $paginationTheme = "bootstrap";
    public $busqueda;

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $proyectos = Proyecto::latest('created_at')
            ->where('user_id',auth()->user()->id)
            ->paginate(10);
        return view('livewire.proyectos-personales', compact('proyectos'));
    }
}

repoJB/resources/views/livewire/ciclos-index.blade.php
<div>
    <div class="card">
        <div class="card-header bg-info p-0 py-2">
            <section class="content-header">
                <h3 class="card-title"><span class="fab fa-fx fa-buffer"></span> Lista de ciclos</h3>
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a class="text-white" href="{{ route('inicio') }}">Inicio</a></li>
                    <li class="breadcrumb-item active text-white-50">Ciclos</li>
                </ol>
            </section>
        </div>
        <div class="card-header">
            <div class="form-group">
                <div class="input-group input-group-lg">
                    <input wire:model="search" type="search" class="form-control form-control-lg"
                        placeholder="Inserte el nombre del ciclo">
                    <div class="input-group-append">
                        <span class="btn btn-lg btn-default">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        @if ($ciclos->count())
            <div class="card-body">
                <table class="table table-striped" id="users">
                    <thead>
                        <tr>
                            <th style="width: 10%">ID</th>
                            <th style="width: 50%">Ciclo Formativo</th>
                            <th style="width: 30%"></th>
                            <th style="width: 20%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($ciclos as $ciclo)
                            <tr>
                                <td>{{ $ciclo->id }}</td>
                                <td>{{ $ciclo->nombre }}</td>
                                <td></td>
                                <td>
                                    <a class="btn btn-primary" href="{{ route('ciclos.show', $ciclo) }}">Ver detalle</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                {{ $ciclos->links() }}
            </div>
        @else
            <div class="card-body">
                <strong>No hay ningún registro...</strong>
            </div>
        @endif
    </div>
</div>

repoJB/resources/views/livewire/proyectos-index.blade.php
<div>
    <div class="card">
        <div class="card-header bg-success p-0 py-2">
            <section class="content-header">
                <h3 class="card-title"><span class="fas fa-fx fa-list"></span> Lista de proyectos</h3>
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a class="text-white" href="{{ route('inicio') }}">Inicio</a></li>
                    <li class="breadcrumb-item active text-white-50">Lista de proyectos</li>
                </ol>
            </section>
        </div>
        <div class="card-header">
            <div class="form-group">
                <div class="input-group input-group-lg">
                    <input wire:model="search" type="search" class="form-control form-control-lg"
                        placeholder="Inserte el nombre del proyecto">
                    <div class="input-group-append">
                        <span class="btn btn-lg btn-default">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        @if ($proyectos->count())
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 11%">
                                Autor
                            </th>
                            <th style="width: 20%">
                                Nombre del proyecto
                            </th>
                            <th>
                                Ciclo Formativo
                            </th>
                            <th>
                                Progreso del proyecto
                            </th>
                            <th>
                                Descargas
                            </th>
                            <th style="width: 8%" class="text-center">
                                Estado
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($proyectos as $proyecto)
                            <tr>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <a href="{{route('perfil',$proyecto->user)}}">
                                                <img alt="Avatar" class="table-avatar" src="{{ $proyecto->user->adminlte_image() }}">
                                            </a>
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    <a href="{{ route('proyectos.show', $proyecto) }}">
                                        {{ $proyecto->nombre }}
                                    </a>
                                    <br />
                                    <small>
                                        Publicado el {{ $proyecto->created_at }}
                                    </small>
                                </td>
                                <td>
                                    <i>{{ $proyecto->ciclo->nombre }}</i>
                                </td>
                                <td class="project_progress">
                                    <div class="progress progress-sm">
                                        @php
                                            $random = rand(0, 100);
                                        @endphp
                                        @if ($random < 25)
                                            <div class="progress-bar bg-success progress-bar-striped progress-bar-animated"
                                                role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0"
                                                aria-valuemax="100" style="width:{{ $random }}%">
                                            </div>

                                        @elseif ($random < 50) <div
                                                class="progress-bar bg-info progress-bar-striped progress-bar-animated"
                                                role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0"
                                                aria-valuemax="100" style="width:{{ $random }}%">
                                    </div>

                                @elseif ($random < 75) <div
                                        class="progress-bar bg-warning progress-bar-striped progress-bar-animated"
                                        role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0"
                                        aria-valuemax="100" style="width:{{ $random }}%">
            </div>

        @elseif ($random <= 100) <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated"
                role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0" aria-valuemax="100"
                style="width:{{ $random }}%">
    </div>
    @endif
</div>
<small>
    {{ $random }}% Completado
</small>
</td>
<td>
    <i class="fas fa-fx fa-cloud-download-alt"> </i> {{ $proyecto->descargas }}
</td>
<td class="project-state">
    @if ($proyecto->publico)
        <span class="badge badge-success">Público</span>
    @else
        <span class="badge badge-danger">Privado</span>
    @endif
</td>
<td class="project-actions text-right">
    <a class="btn btn-primary btn-sm" href="{{ route('proyectos.show', $proyecto) }}">
        <i class="fas fa-eye">
        </i>
        Ver proyecto
    </a>
</td>
</tr>
@endforeach
</tbody>
</table>
</div>
<div class="card-footer">
    {{ $proyectos->links() }}
</div>
@else
<div class="card-body">
    <strong>No hay ningún registro...</strong>
</div>
@endif
</div>

</div>

repoJB/resources/views/livewire/proyectos-personales.blade.php
<div>
    <div class="card">
        <div class="card-header bg-success p-0 py-2">
            <section class="content-header">
                <h3 class="card-title"><span class="fas fa-fx fa-list"></span> Mis proyectos</h3>
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a class="text-white" href="{{ route('inicio') }}">Inicio</a></li>
                    <li class="breadcrumb-item active text-white-50">Mis proyectos</li>
                </ol>
            </section>
        </div>
        <div class="card-header">
            <div class="form-group">
                <div class="input-group input-group-lg">
                    <input wire:model="busqueda" type="search" class="form-control form-control-lg"
                        placeholder="Inserte el nombre del proyecto">
                    <div class="input-group-append">
                        <span class="btn btn-lg btn-default">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        @if ($proyectos->count())
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 11%">
                                Autor
                            </th>
                            <th style="width: 20%">
                                Nombre del proyecto
                            </th>
                            <th>
                                Progreso del proyecto
                            </th>
                            <th>
                                Ciclo Formativo
                            </th>
                            <th style="width: 8%" class="text-center">
                                Estado
                            </th>
                            <th style="width: 1%">
                            </th>
                            <th style="width: 10%">
                            </th>
                            <th style="width: 8%">
                            </th>
                            <th style="width: 10%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($proyectos as $proyecto)
                            <tr>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar"
                                                src="{{ $proyecto->user->profile_photo_path }}">
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    <a href="{{ route('proyectos.show', $proyecto) }}">
                                        {{ $proyecto->nombre }}
                                    </a>
                                    <br />
                                    <small>
                                        Publicado el {{ $proyecto->created_at }}
                                    </small>
                                </td>
                                <td class="project_progress">
                                    <div class="progress progress-sm">
                                        @php
                                            $random = rand(0, 100);
                                        @endphp
                                        @if ($random < 25)
                                            <div class="progress-bar bg-success progress-bar-striped progress-bar-animated"
                                                role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0"
                                                aria-valuemax="100" style="width:{{ $random }}%">
                                            </div>

                                        @elseif ($random < 50) <div
                                                class="progress-bar bg-info progress-bar-striped progress-bar-animated"
                                                role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0"
                                                aria-valuemax="100" style="width:{{ $random }}%">
                                    </div>

                                @elseif ($random < 75) <div
                                        class="progress-bar bg-warning progress-bar-striped progress-bar-animated"
                                        role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0"
                                        aria-valuemax="100" style="width:{{ $random }}%">
            </div>

        @elseif ($random <= 100) <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated"
                role="progressbar" aria-valuenow="{{ $random }}" aria-valuemin="0" aria-valuemax="100"
                style="width:{{ $random }}%">
    </div>
    @endif
</div>
<small>
    {{ $random }}% Completado
</small>
</td>
<td>
    <i>{{ $proyecto->ciclo->nombre }}</i>
</td>
<td class="project-state">
    @if ($proyecto->publico)
        <span class="badge badge-success">Público</span>
    @else
        <span class="badge badge-danger">Privado</span>
    @endif
</td>
<td></td>
<td class="project-actions text-right">
    <a class="btn btn-primary btn-sm" href="{{ route('proyectos.show', $proyecto) }}">
        <i class="fas fa-eye">
        </i>
        Ver proyecto
    </a>
</td>
<td>
    <a class="btn btn-info btn-sm" href="{{route('proyectos.edit',$proyecto)}}">
        <i class="fas fa-pencil-alt">
        </i>
        Editar
    </a>
</td>
<td>
    <form class="formulario-eliminar" action="{{ route('proyectos.destroy', $proyecto) }}" method="POST">
        @csrf
        @method('DELETE')
        <button class="btn btn-danger btn-sm" type="submit"><i class="fas fa-trash">
            </i>Eliminar</button>
    </form>
</td>
</tr>
@endforeach
</tbody>
</table>
</div>
<div class="card-footer">
    {{ $proyectos->links() }}
</div>
@else
<div class="card-body">
    <strong>No tienes nada registrado... &#128524; ¡Ánimate y sube tu proyecto personal! &#128515;</strong>
</div>
@endif
</div>

</div>