repoJB/routes/admin.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::get('',[HomeController::class,'index'])->name('inicio');

Route::resource('users',UserController::class)->only(['index','edit','update'])->names('admin.users');

repoJB/routes/web.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CicloController;
use App\Http\Controllers\PerfilController;
use App\Http\Controllers\ProyectoController;
use Illuminate\Support\Facades\Route;
use App\Models\Proyecto;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->user()) {
        return view('index');
    }
    return view('welcome');
})->name('home');

Route::middleware(['auth:sanctum', 'verified'])->get('ciclos', [CicloController::class, 'index'])->name('ciclos.index');

Route::middleware(['auth:sanctum', 'verified'])->get('ciclos/{ciclo}', [CicloController::class, 'show'])->name('ciclos.show');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/mis-proyectos', [ProyectoController::class, 'personales'])->name('proyectos.personales');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/step', [ProyectoController::class, 'step'])->name('proyectos.step');

Route::middleware(['auth:sanctum', 'verified'])->post('proyectos/{proyecto}/comentar', [ProyectoController::class, 'comentar'])->name('proyectos.comentar');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/{proyecto}/eliminarComentario', [ProyectoController::class, 'eliminarComentario'])->name('proyectos.eliminarComentario');

Route::resource('proyectos', ProyectoController::class)->names('proyectos')->middleware(['auth:sanctum', 'verified']);

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/{proyecto}/descargar', [ProyectoController::class, 'download'])->name('proyectos.download');

Route::middleware(['auth:sanctum', 'verified'])->get('proyectos/{proyecto}/descargarLogo', [ProyectoController::class, 'descargarLogo'])->name('proyectos.descargarLogo');

Route::middleware(['auth:sanctum', 'verified'])->get('perfil/{user}', [PerfilController::class, 'index'])->name('perfil');

/*Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');*/

repoJB/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

repoJB/resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

repoJB/resources/views/index.blade.php
@extends('adminlte::page')

@section('title', 'Inicio')

@section('content_header')
    <div>
        <h1 class="text-center inline-block">
            Bienvenidos al
            <strong>Repositorio</strong>
            <p class="text-xl" style="letter-spacing: -4pt;white-space: nowrap;">
                <span style="color: red">J</span>
                <span style="color: black">B</span>
            </p>
        </h1>
    </div>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-primary">
                <div class="inner">
                    <h3>COMPARTE</h3>
                    <p>Sube a la nube tus proyectos</p>
                </div>
                <div class="icon">
                    <i class="fas fa-arrow-circle-up"></i>
                </div>
                <a href="{{route('proyectos.create')}}" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
                <div class="inner">
                    <h3>EXPLORA</h3>

                    <p>Busca proyectos de otros usuarios</p>
                </div>
                <div class="icon">
                    <i class="fas fa-search"></i>
                </div>
                <a href="{{route('proyectos.index')}}" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
                <div class="ribbon-wrapper ribbon-xl">
                    <div class="ribbon bg-danger text-lg">
                        En desarrollo
                    </div>
                </div>
                <div class="inner">
                    <h3>GESTIONA</h3>

                    <p>Organiza las tareas de tu proyecto</p>
                </div>
                <div class="icon">
                    <i class="fas fa-calendar-alt"></i>
                </div>
                <a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->

            <div class="small-box bg-danger">
                <div class="ribbon-wrapper ribbon-xl">
                    <div class="ribbon bg-warning text-lg">
                        En desarrollo
                    </div>
                </div>
                <div class="inner">
                    <h3>EJECUTA</h3>

                    <p>Despliega cualquier aplicación</p>
                </div>
                <div class="icon">
                    <i class="fas fa-cog"></i>
                </div>
                <a href="#" class="small-box-footer">Más información <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
    </div>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    
@stop

repoJB/resources/views/navigation-dropdown.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100 shadow">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('home') }}">
                        <x-jet-application-mark class="block h-9 w-auto" />
                    </a>
                </div>

                <!-- Navigation Links -->
                {{-- <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-jet-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-jet-nav-link>
                </div> --}}
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                @auth
                <x-jet-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                            <button class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition duration-150 ease-in-out">
                                <img class="h-8 w-8 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                            </button>
                        @else
                            <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                                <div>{{ Auth::user()->name }}</div>

                                <div class="ml-1">
                                    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                        <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                    </svg>
                                </div>
                            </button>
                        @endif
                    </x-slot>

                    <x-slot name="content">
                        <!-- Account Management -->
                        <div class="block px-4 py-2 text-xs text-gray-400">
                            {{ __('Manage Account') }}
                        </div>

                        <x-jet-dropdown-link href="{{ route('profile.show') }}">
                            {{ __('Profile') }}
                        </x-jet-dropdown-link>

                        @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                            <x-jet-dropdown-link href="{{ route('api-tokens.index') }}">
                                {{ __('API Tokens') }}
                            </x-jet-dropdown-link>
                        @endif

                        <div class="border-t border-gray-100"></div>

                        

                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-jet-dropdown-link href="{{ route('logout') }}"
                                                onclick="event.preventDefault();
                                                            this.closest('form').submit();">
                                {{ __('Logout') }}
                            </x-jet-dropdown-link>
                        </form>
                    </x-slot>
                </x-jet-dropdown>
                @else
                <a href="{{ route('login') }}" class="text-sm text-gray-700 underline">Iniciar sesión</a>
                <a href="{{ route('register') }}" class="ml-4 text-sm text-gray-700 underline">Registrarse</a>
                @endauth
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        {{-- <div class="pt-2 pb-3 space-y-1">
            <x-jet-responsive-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-jet-responsive-nav-link>
        </div> --}}

        <!-- Responsive Settings Options -->
        @auth
            
       
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <img class="h-10 w-10 rounded-full" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                </div>

                <div class="ml-3">
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Account Management -->
                <x-jet-responsive-nav-link href="{{ route('profile.show') }}" :active="request()->routeIs('profile.show')">
                    {{ __('Profile') }}
                </x-jet-responsive-nav-link>

                @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                    <x-jet-responsive-nav-link href="{{ route('api-tokens.index') }}" :active="request()->routeIs('api-tokens.index')">
                        {{ __('API Tokens') }}
                    </x-jet-responsive-nav-link>
                @endif

                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-jet-responsive-nav-link href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                        {{ __('Logout') }}
                    </x-jet-responsive-nav-link>
                </form>

                
            </div>
        </div>
        @else
        <div class="py-1 border-t border-gray-200">
            <x-jet-responsive-nav-link href="{{ route('login') }}" :active="request()->routeIs('login')">
               Iniciar Sesión
            </x-jet-responsive-nav-link>
            <x-jet-responsive-nav-link href="{{ route('register') }}" :active="request()->routeIs('register')">
                Registrarse
            </x-jet-responsive-nav-link>
        </div>
        @endauth
    </div>
</nav>

repoJB/resources/views/perfil.blade.php
@extends('adminlte::page')

@section('title', 'Perfil')
@section('content')
    <div class="card card-widget widget-user shadow">
        <div class="widget-user-header bg-info">
            <div style="top:0;right:0;">
                <button class="btn btn-warning float-right">
                    <i class="fas fa-edit"></i>
                </button>
            </div>
            <h3 class="widget-user-username">{{ $user->name }}</h3>
            <h5 class="widget-user-desc">{{ $user->adminlte_desc() }}</h5>
        </div>
        <div class="widget-user-image">
            <img class="img-circle elevation-2" src="{{ $user->adminlte_image() }}" alt="User Avatar">
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-sm-4 border-right">
                    <div class="description-block">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title text-muted">Proyectos personales</h3>
                                <h3><span class="badge badge-warning float-right">{{ $user->proyectos->count() }}</span>
                                </h3>
                            </div>

                            @if ($user->proyectos->count())
                                <div id="accordion">
                                    @foreach ($user->proyectos as $proyecto)

                                        <div class="card card-gray collapsed-card ml-3 mr-3 mt-3">
                                            <div class="card-header row">
                                                <h3 class="col-sm-11 card-title">{{ $proyecto->nombre }}</h3>

                                                <div class="col-sm-1 card-tools">
                                                    <button type="button" class="btn btn-tool"
                                                        data-card-widget="collapse"><i class="fas fa-plus"></i>
                                                    </button>
                                                </div>
                                            </div>
                                            <div class="card-body" style="display: none;">
                                                {!! $proyecto->descripcion !!}
                                                <br>
                                                <small><i class="fas fa-graduation-cap"> Ciclo formativo :</i>
                                                    {{ $proyecto->ciclo->nombre }}</small>
                                                <br>
                                                <small><i class="fas fa-fx fa-cloud-download-alt"> Descargas :</i>
                                                    {{ $proyecto->descargas }}</small>
                                                <br>
                                                @if ($proyecto->publico)
                                                    <small><i class="fas fa-lock-open"> Público</i></small>
                                                    <br>
                                                @else
                                                    <small><i class="fas fa-lock"> Privado</i></small>
                                                    <br>
                                                @endif
                                                <a href="{{ route('proyectos.show', $proyecto) }}"
                                                    class="btn btn-warning mb-1 mt-2">Ver proyecto</a>
                                            </div>
                                        </div>

                                    @endforeach
                                </div>
                            @else
                                <div class="card pt-2 mt-2 ml-2 mr-2">
                                    <p class="text-center m-auto">
                                        <strong>Este usuario no tiene ningún proyecto subido</strong>
                                    </p>
                                </div>
                            @endif

                        </div>
                    </div>
                </div>
                <div class="col-sm-4 border-right">
                    <div class="description-block">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title text-muted">Información del perfil</h3>
                            </div>
                            <div class="card-body">
                                <div class="info-box shadow-sm">
                                    <span class="info-box-icon bg-danger"><i class="fas fa-cloud-upload-alt"></i></span>
                                    <h3><span class="badge bg-danger"></span></h3>
                                    <div class="info-box-content">
                                        <span class="info-box-text"><strong>Proyectos personales</strong></span>
                                        <span class="info-box-number text-muted">{{ $user->proyectos->count() }}</span>
                                    </div>
                                </div>
                                <hr>
                                <div class="info-box shadow-sm">
                                    <span class="info-box-icon bg-danger"><i class="fas fa-envelope"></i></span>
                                    <h3><span class="badge bg-danger"></span></h3>
                                    <div class="info-box-content">
                                        <span class="info-box-text"><strong>Email</strong></span>
                                        <span class="info-box-number text-muted">{{ $user->email }}</span>
                                    </div>
                                </div>
                                <hr>
                                <div class="info-box shadow-sm">
                                    <span class="info-box-icon bg-danger"><i class="fas fa-map-marker-alt"></i></span>
                                    <h3><span class="badge bg-danger"></span></h3>
                                    <div class="info-box-content">
                                        <span class="info-box-text"><strong>Localidad</strong></span>
                                        <span class="info-box-number text-muted">{{ $user->localidad }}</span>
                                    </div>
                                </div>
                                <hr>
                                <div class="info-box shadow-sm">
                                    <span class="info-box-icon bg-danger"><i class="fas fa-pencil-alt"></i></span>
                                    <h3><span class="badge bg-danger"></span></h3>
                                    <div class="info-box-content">
                                        <span class="info-box-text"><strong>Sobre mí</strong></span>
                                        <span class="info-box-number text-muted">Lorem ipsum dolor sit amet, consectetur
                                            adipisicing elit. Qui atque labore numquam magnam sunt dolore laboriosam, odit
                                            hic voluptas quae exercitationem expedita consectetur, molestias iusto, aliquid
                                            quibusdam et ex molestiae.</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="description-block">
                        <h5 class="description-header">PENSAR QUE PONER AQUÍ</h5>
                        <span class="description-text">MÁS DE LO MISMO</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');

    </script>
@stop